apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ctQXJmsd/b2EOP0Q5AsL5yTMWJF8uCBAY5LoRcrX8WjacK5yhNzVT/5+vVA=,iv:x7+WERzHQO/eY5Crqp45tDWow8iS9FDg5FV5yIBLCTY=,tag:pQsVPE0uUAA6Dt5khN8i6A==,type:str]
kind: Secret
metadata:
    name: cilium-bgp-auth-secret
    namespace: kube-system
type: string
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dndHdlZ4cEI1aDlvZWpX
            S0tKWEdrYnMraDdoRThjMmVVWFlXczFISEJFCmlxMm9iUVVFUmk3a3p6eCttRFAx
            aTdvU2Uya1IyOUt1OFdQcDdHbldGbVkKLS0tIFc5aC9oNnNra1FtaWdwTktpUEND
            RW1xRUlPR0o2eExDVThYVHAxQkpBSE0KvSobhpUsfh/qfcviBtwM5iJT8WYGECUJ
            fvxqE5WyI5nBW0eH0Kio0w5Ps66DZTBgs+sXCk4tbXEem+YMJyEvCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T10:43:53Z"
    mac: ENC[AES256_GCM,data:wrpwxT4aW/nrgYbBeuzLpsma+y+U/3LQAXP1tx399AQ7YRa2/XJzWrGfZtzdYvJTRdkKMhkcJehNnS/yo5xs9lBqgejm72jgVSXU2Jb4wE2dVDMZnCEiqfhwZsavXT24/oOMmtsVctY3FjGJDfcBYU9FKJPU8XqCYBrOoyOszBI=,iv:pTzOIzS8fwZkRdVONSKkLafFZ84Pv/12vbnwj1UDETA=,tag:v90NYzXYZDX//7087kAPFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
