apiVersion: v1
stringData:
    age.agekey: ENC[AES256_GCM,data:36UykOyzFQimm75lzuT9R9FQtdep92XOmYcdIGUSAGgKKfD8W2msFsnz2RN+vs0YLIQDvuqRMAm9XhfhDvztPGIYMCHRzGoRT30=,iv:rcC+qfaua1SuxLy8EYbPsCD/IB+xyS+9s6zWBSCzt28=,tag:k60ZfswJt+xovu8Q9m6U/g==,type:str]
kind: Secret
metadata:
    name: sops-age
type: Opaque
sops:
    age:
        - recipient: age1mne6jzrry0jeu07v6k74np9dxh6c5mrwhyhr9lruxuwhlwcsyg7qujh6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYTh1aXRkV2FjT2toQzN6
            MlJEMHk5cTNBSkNuZHh2V1ZiMFhoTGFneTBRCnpTdkhBRU9SbllZRHpWZUFRanZr
            bXRhV3RDMC9ETG9uaXNnQko2YXBTTnMKLS0tIHhvNExEeGtWcjBVaFp1T1lKSFJI
            aVhUaTlhMkk5NmNaSVpZTFhpSWxzajAK+n9cgiYGMridvcrt9tGG4LfbDyE/P7Yb
            yfEClwW8Yt1BUu2ouGNxMPwn+YfW0eWvNOVuXdkT9ittB9EK58WWQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T20:25:56Z"
    mac: ENC[AES256_GCM,data:93AZrupgJyT9LRiCwdnzqF01tm1au3fOZVcxM3DjqdFUTp0EN2SnYswzFDVYbiwRb9HOawvaXpLJ5gZEbB3UlFvOO8U8MfP8lIy8cB450mY6mI2BeWNUz1oeQ6gAePbmduqEYpDdadW5XkkCORw3mCrb1Z548p4o8mX8WF7bvXk=,iv:6PP0mCN0qe80XMK/I9MsWLR4IEF76jglz7UEOTDVrKM=,tag:BeO763k1D4GRt6/MPbgqvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:CY4x,iv:1Hh50BU38pQxUqNXRxzYPDI0UlQQhw6BbwJJzu3PS2Q=,tag:F4VM4X2laYgUetWjSKq3Jw==,type:str]
    password: ENC[AES256_GCM,data:io/AMfPd//URDeD+Cgik58sdWQYsc9V5APwft3fcW2iZFTttrbNW3KPgVA5QFyXY6bkqgGDVHXiK+dvJXmVkcBl7SUFJvAipUG2Jcl7K/Iz8vvbrNLGef279ls6L,iv:5XifRH15FUCa82ajSJJ4MmGqAX3KTUOV+2XKroH51Rs=,tag:JrCzfOlWzOyuOraDM8qT+Q==,type:str]
kind: Secret
metadata:
    name: git-auth
type: Opaque
sops:
    age:
        - recipient: age1mne6jzrry0jeu07v6k74np9dxh6c5mrwhyhr9lruxuwhlwcsyg7qujh6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYTh1aXRkV2FjT2toQzN6
            MlJEMHk5cTNBSkNuZHh2V1ZiMFhoTGFneTBRCnpTdkhBRU9SbllZRHpWZUFRanZr
            bXRhV3RDMC9ETG9uaXNnQko2YXBTTnMKLS0tIHhvNExEeGtWcjBVaFp1T1lKSFJI
            aVhUaTlhMkk5NmNaSVpZTFhpSWxzajAK+n9cgiYGMridvcrt9tGG4LfbDyE/P7Yb
            yfEClwW8Yt1BUu2ouGNxMPwn+YfW0eWvNOVuXdkT9ittB9EK58WWQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T20:25:56Z"
    mac: ENC[AES256_GCM,data:93AZrupgJyT9LRiCwdnzqF01tm1au3fOZVcxM3DjqdFUTp0EN2SnYswzFDVYbiwRb9HOawvaXpLJ5gZEbB3UlFvOO8U8MfP8lIy8cB450mY6mI2BeWNUz1oeQ6gAePbmduqEYpDdadW5XkkCORw3mCrb1Z548p4o8mX8WF7bvXk=,iv:6PP0mCN0qe80XMK/I9MsWLR4IEF76jglz7UEOTDVrKM=,tag:BeO763k1D4GRt6/MPbgqvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
