apiVersion: v1
stringData:
    age.agekey: ENC[AES256_GCM,data:YD9VdgqoWj5STduY1NkWHQ5tmhV/mBllY3I9k6JKGlBmZSSSf59Qu3LaxgYmRRH3JQYsYj9TmlYfYlLaYb9W6ojQ59OVBHI3KemLFqlUXOGR9pQ4koP0sRijkf3DZGN2nP131TlUslPq/m9aoIuN/Mxav0bxMAuXc4vXWtPeHZjjX3oyUYztSX89TJrrXFrkG9PVL61exqNo9MNmtgd4//EPLzBOPFiKEtM5/3gOw9cx6mXy59WKjVqP9cCxR+VwDCt1kozDWS+lYxCcmqRs,iv:4C8BEKVcaFxkcEaMJBjx2xop6P+/BWnvfAxOiaOuB3U=,tag:ySIijwYsBAR92ca1itU4gw==,type:str]
kind: Secret
metadata:
    name: sops-age
type: Opaque
sops:
    age:
        - recipient: age1mne6jzrry0jeu07v6k74np9dxh6c5mrwhyhr9lruxuwhlwcsyg7qujh6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbE9CK0ZWUmF4S1FsWU5y
            MVhtMmZLaEZzbjB6Wll2S1RUSVhaZnd1c1JVCk9LcVl0cU9NWUpmamxMeFFYY0tE
            NzN1Q09uYTlGLzc3RkR5QVJNLzRXYUEKLS0tIDQyZ2JwdFpWNEF0QUlwV3R0eEN1
            d3ZLdWRjREtUOFFmclFWd3pEcnhpSDQK7bGfbG/ZTJGqhNE9H1NxEvQwdRem1g0p
            R5aKxTEt55c5xQvz3ge/vLBaIMTEPBKXH6cnSYmxHh4IQ1Io9mH2cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T20:15:03Z"
    mac: ENC[AES256_GCM,data:JdOa6uiu6q1v7Ig21F9hU7+YzQWNld+n/EkE+6At9C/CUVVUYC21HUyn0SAelcQrrghrofxhOZxfF/wLF+LMETtcCyF55qOTtL8SLCcRC2jO1kzU7kcStQM7jDY+ukzYvKGRIinyQH1TT8Xx5oYoM7DXyexDnUHFyAPIIZo0TMI=,iv:sUZFKfl5uOo3WUrY9617pIG6v86+eNaDPjqsLpnI+h4=,tag:qdGPoqnl5r/AUS1KKPCkjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:+T2G,iv:IvKzAa9sihofgK84fI3+lhH1HdP+DpM/eH9OE2yl4ho=,tag:Z66ui5VxSGHLflHOX0GSPA==,type:str]
    password: ENC[AES256_GCM,data:O+IshIUX8RSogoUlhtwvXDMmiGxtdCwxh2lGfiKs352sBoca+uORHdB2k888fPJcbmDz6SVtwdAtDr1DS5VGQepMuFJaLrJN8MSxOvA+nA5ZfMv+vOHzzl4IIxeb,iv:UMmck/fPeWjHM7JL1/yp95ol/TDlOpIgGq9Ovmr1yZw=,tag:/0WfAEwnvo9NnM2MFTSOYA==,type:str]
kind: Secret
metadata:
    name: git-auth
type: Opaque
sops:
    age:
        - recipient: age1mne6jzrry0jeu07v6k74np9dxh6c5mrwhyhr9lruxuwhlwcsyg7qujh6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbE9CK0ZWUmF4S1FsWU5y
            MVhtMmZLaEZzbjB6Wll2S1RUSVhaZnd1c1JVCk9LcVl0cU9NWUpmamxMeFFYY0tE
            NzN1Q09uYTlGLzc3RkR5QVJNLzRXYUEKLS0tIDQyZ2JwdFpWNEF0QUlwV3R0eEN1
            d3ZLdWRjREtUOFFmclFWd3pEcnhpSDQK7bGfbG/ZTJGqhNE9H1NxEvQwdRem1g0p
            R5aKxTEt55c5xQvz3ge/vLBaIMTEPBKXH6cnSYmxHh4IQ1Io9mH2cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T20:15:03Z"
    mac: ENC[AES256_GCM,data:JdOa6uiu6q1v7Ig21F9hU7+YzQWNld+n/EkE+6At9C/CUVVUYC21HUyn0SAelcQrrghrofxhOZxfF/wLF+LMETtcCyF55qOTtL8SLCcRC2jO1kzU7kcStQM7jDY+ukzYvKGRIinyQH1TT8Xx5oYoM7DXyexDnUHFyAPIIZo0TMI=,iv:sUZFKfl5uOo3WUrY9617pIG6v86+eNaDPjqsLpnI+h4=,tag:qdGPoqnl5r/AUS1KKPCkjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
