apiVersion: v1
stringData:
    age.agekey: ENC[AES256_GCM,data:9kixNeL68Fl3fyZ5etibQgAl1haTelDDG+qvQNVSTfguvKCy636m03TQkyAW3+U0C/bEGiB5/jG0NXf2e3lK8OG7ND6OkxOA83I=,iv:LohJDeNLICRUwRlgXyaOy3WLwMtBYzR2PiMsFvVvKxo=,tag:bJkrO6eFTrRtEl/k4DHGpg==,type:str]
kind: Secret
metadata:
    name: sops-age
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUURRRjR3czBCcmdkbnpy
            dWl2TWk5a2VYYjBTRGpkeUNXb3g5cFViK3p3Cjd4dDEvQ1FyMFRVdWJHOStseFY0
            U1NmVVRUU3ZDdEUzMTdOeE4zaDJNbncKLS0tIEZnWHR1ZmQrK2ZreHB0MStDdWUx
            VnFOL2NTYmJISUN6eThYM0JYUDd5OXMKKoP+SSpbDExe8xXEXmjcfKkHdW2cRYYe
            iWFFbg1XusK+2V65qBQHnxz7dUCbR/amjbZ6Ca/VYb9IT4VA3Z3t1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T20:46:39Z"
    mac: ENC[AES256_GCM,data:GmlEK5rM4YQYc/a5ofb5to4hLfOPV2+cpn70Zcey6W8fbjUJbnB9ZBsapzW6MjIE98JTt72oyczl2q1Ttt0UxF8o7Y+orAwb0OuGWTl0ccoM3OsDgPynAyiW7Xk9VTzUcI6QmjJkWvVN9RC1dHvij9Kcb4Kq9+30EUYFVsF1jQM=,iv:eBVO4vlryVzZS3RKqtslsT3Nqb5GFHfUECtRbzoXk/4=,tag:C8g7AgaFDxEYF72hDmiKPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:5wpj,iv:+E/Z+mDVwaDxeqm7U0aPexq19Hk3Hl7qu/JGV7CcHYw=,tag:uvJotHW6zob3uylcC7ChNg==,type:str]
    password: ENC[AES256_GCM,data:WMQaMILcit9kXZaOl/i+PgJ8Kg07JO0tL8YWwB5tx50+bx/5akV4RWj1FLcYX1LSSAUzBY4mo+SQKIn8vDyUNICDT2K6oORHwTVh+6HTBbZ5wKlMfDHQspBppC/x,iv:YqPc623xaJLhLPcdkoJLzJsOX+ei9ksegvtjJHZxTRE=,tag:WUEwDdO+95oi4zRkSObORA==,type:str]
kind: Secret
metadata:
    name: git-auth
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUURRRjR3czBCcmdkbnpy
            dWl2TWk5a2VYYjBTRGpkeUNXb3g5cFViK3p3Cjd4dDEvQ1FyMFRVdWJHOStseFY0
            U1NmVVRUU3ZDdEUzMTdOeE4zaDJNbncKLS0tIEZnWHR1ZmQrK2ZreHB0MStDdWUx
            VnFOL2NTYmJISUN6eThYM0JYUDd5OXMKKoP+SSpbDExe8xXEXmjcfKkHdW2cRYYe
            iWFFbg1XusK+2V65qBQHnxz7dUCbR/amjbZ6Ca/VYb9IT4VA3Z3t1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T20:46:39Z"
    mac: ENC[AES256_GCM,data:GmlEK5rM4YQYc/a5ofb5to4hLfOPV2+cpn70Zcey6W8fbjUJbnB9ZBsapzW6MjIE98JTt72oyczl2q1Ttt0UxF8o7Y+orAwb0OuGWTl0ccoM3OsDgPynAyiW7Xk9VTzUcI6QmjJkWvVN9RC1dHvij9Kcb4Kq9+30EUYFVsF1jQM=,iv:eBVO4vlryVzZS3RKqtslsT3Nqb5GFHfUECtRbzoXk/4=,tag:C8g7AgaFDxEYF72hDmiKPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
