---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: market-team
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    istio.io/dataplane-mode: ambient
  name: shop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: market-team
  name: market-team
  namespace: shop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: market-team
  name: market-team-reconciler
  namespace: shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:shop:reconciler
- kind: ServiceAccount
  name: market-team
  namespace: shop
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  labels:
    toolkit.fluxcd.io/tenant: market-team
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "4"
    requests.memory: 8Gi
    limits.memory: 8Gi
    pods: "9"
    persistentvolumeclaims: "9"
    requests.storage: 100Gi
    configmaps: "20"
    secrets: "20"
    services: "20"