---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    istio.io/dataplane-mode: ambient
  name: policy-reporter
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  interval: 1m
  url: https://kyverno.github.io/policy-reporter/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: policy-reporter
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
  interval: 1m
  timeout: 10m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  values:
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 75Mi
        cpu: 5m
    ui:
      enabled: true
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
      resources:
        limits:
          memory: 256Mi
          cpu: 200m
        requests:
          memory: 75Mi
          cpu: 5m
      networkPolicy:
        enabled: true
        ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: traefik
            ports:
            - protocol: TCP
              port: 8080
            - port: 15008
              protocol: TCP
        egress:
          - {}
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
        effect: NoSchedule
    networkPolicy:
      enabled: true
      ingress:
        - from:
            - podSelector: {}
      egress:
        - {}
