---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: longhorn-system
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: "1.10.2"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 1m
  timeout: 15m
  values:
    global:
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
    persistence:
      defaultClass: false
      defaultFsType: ext4
      defaultClassReplicaCount: 2
      defaultDataLocality: disabled
      dataEngine: v1
    #networkPolicies:
    #  enabled: yes
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      defaultDataPath: "/var/mnt/longhorn/"
      replicaSoftAntiAffinity: false
      replicaAutoBalance: "least-effort"
      rwxVolumeFastFailover: true
      replicaZoneSoftAntiAffinity: true
      storageOverProvisioningPercentage: "100"
      concurrentAutomaticEngineUpgradePerNodeLimit: "1"
      storageMinimalAvailablePercentage: "25"
      defaultReplicaCount: "2"
      autoSalvage: false
      autoCleanupSystemGeneratedSnapshot: true
      defaultDataLocality: "best-effort"
      allowCollectingLonghornUsageMetrics: false
      storageReservedPercentageForDefaultDisk: "15"
      engineReplicaTimeout: "30"
      taintToleration: '"node-role.kubernetes.io/infra:NoSchedule"'
      #systemManagedComponentsNodeSelector: '"node-role.kubernetes.io/infra:"'
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9500"
    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    longhornUI:
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    defaultBackupStore:
      backupTargetCredentialSecret: "backup-secret"
      backupTarget: "s3://t-eits-lh@garage/"
