---
apiVersion: v1
stringData:
    age.agekey: ENC[AES256_GCM,data:YCzzGDrWDDEHbwtx3Vbzt1xvaxMdgF/LldVZzSnR9ag6mDww60dnizdCkjqCBdQ1PhIqwk7OGj5SLuUiRNNl6FLVSE0G8zKVE4A=,iv:chUPV6ub9z8KS/lO6xNcsdMTc6GjNf6bf6uBCPNu+HE=,tag:iHZkoD5gxVrEXhIvsq2Vhg==,type:str]
kind: Secret
metadata:
    name: sops-age
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ0FqY21jSUFiM0dDTUhC
            dVE5Z09NZ2Z6VjRwNm43WWhxODBVYUJUZDBBClhGKzQxQUFtRzEzYkp4SEsyaS9s
            WWxKTXBLQlBXaGFtckNMTWFteWRoNEEKLS0tIG1LUE0xRzFLbDZaNDlaZW1KQUVJ
            bW9saVkwYUEvRVFaSDFLbzlXYWZuU3cKJC7oVVFXYxTbASgdReA8j/EpxccWuaFp
            7lPwK/STrevlEkUywmmK3pxPlLtujl0E7l5qu75ZgNIrPk7xEgjCkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T17:27:11Z"
    mac: ENC[AES256_GCM,data:tWpLdR5q4oFoK98Hgcye9wXEl2GNQJM5F7IqHjNVJrQFwawPrYJKLpV6aRaxlgc4dB467AsYMcQX7KhqBsyqkw5SZp/qasGB+58K/fzjah2Hvb8TdLcAAxELAnDcNVLtaUTJ7YnSDZzDtw3Al7KQLXT2ttlHO83ufhOaucfzG4w=,iv:+NDTpIVkhtPD/HTgLYHzhB7Sxo9vJvIknIvTNzxrlWM=,tag:rvNSU+EaEE8uQCHzPCOiSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:yuQd,iv:zxU0cbkIxHWYfob0TWaYkbSd1SSk/MMxdqOOlSx2kuU=,tag:JANJC8pgNx58/Q7ft24eDw==,type:str]
    password: ENC[AES256_GCM,data:8/XD8CpoyTpR1i6IWY3KwV+6qStxx0ckHKXJbjE57+QkUHtNDNAD/ThkiVtTrtYOQdpCvHWphU5myyGTJf0cdf4S9ekWSky0t3RGc7hB0KVGcfCmbICTsLnDD3IT,iv:q7/+52MsnaUVXKxXeTDx9KEFJ6szbLu+F5X4ikaBGCg=,tag:wnxI3b6gR0WvhwIQdgkEig==,type:str]
kind: Secret
metadata:
    name: git-auth
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNzJTY05lN29TL2ZWdlE5
            NDd1dHBSNzF5bXhsbjZEVkI1THNXd2hpT3pnCm12Q2V5NFYwU3VtUGpyMTRxNkls
            R2tHbGhQeHRVMk4ySmVQMVBueG8yck0KLS0tIG94KzRxeXFxMnZWcjB2MFdTdjMz
            OFBoSHk2TVc3YU13NWxyTHBSNy9OYkkKsYJ+2ME0AJmJBI4YWRU4tQ7nF0nV8Y/8
            A9OnEO2qTmwH80X0nxClhAoqQ7NSRNi3lq0M4Tdz612gWTgiLlJx1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T07:24:12Z"
    mac: ENC[AES256_GCM,data:F6qo12ujMlZV8Y3tsyzo9qwSDYKV1PyKm1mssFUbXEv002yiGrat81ABvJa/vMsn0kgKHM9aKdyxz/8LUMxyNvUcm7Au5VtqOpqCDA+1GtDBcDevmShKyuuVY3cs1J/uNuVzhNEwBsc6IscnomrDNytGc9rdRMEUnGXU+O/eY0U=,iv:q6B6FNKGn/qz5OauHTuwRBPgSw9JNt+zh8I4j8fXcRA=,tag:atu/z1aaiT5tNoA0QjbC+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
