---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
  name: kiali-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 1m
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: kiali-operator
  releaseName: kiali-operator
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  interval: 1m
  values:
    onlyViewOnlyMode: true
    cr:
      create: true
      namespace: kiali-operator
      spec:
        auth:
          strategy: "anonymous"
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
        effect: NoSchedule
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 64Mi
        cpu: 10m