---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cloud-team
  - ../base/market-team
patches:
  - path: cloud-team-patch.yaml
  - path: market-team-patch.yaml
  decryption:
    provider: sops
    secretRef:
      name: sops-age