---
apiVersion: v1
stringData:
    age.agekey: ENC[AES256_GCM,data:YCzzGDrWDDEHbwtx3Vbzt1xvaxMdgF/LldVZzSnR9ag6mDww60dnizdCkjqCBdQ1PhIqwk7OGj5SLuUiRNNl6FLVSE0G8zKVE4A=,iv:chUPV6ub9z8KS/lO6xNcsdMTc6GjNf6bf6uBCPNu+HE=,tag:iHZkoD5gxVrEXhIvsq2Vhg==,type:str]
kind: Secret
metadata:
    name: sops-age
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ0FqY21jSUFiM0dDTUhC
            dVE5Z09NZ2Z6VjRwNm43WWhxODBVYUJUZDBBClhGKzQxQUFtRzEzYkp4SEsyaS9s
            WWxKTXBLQlBXaGFtckNMTWFteWRoNEEKLS0tIG1LUE0xRzFLbDZaNDlaZW1KQUVJ
            bW9saVkwYUEvRVFaSDFLbzlXYWZuU3cKJC7oVVFXYxTbASgdReA8j/EpxccWuaFp
            7lPwK/STrevlEkUywmmK3pxPlLtujl0E7l5qu75ZgNIrPk7xEgjCkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T17:27:11Z"
    mac: ENC[AES256_GCM,data:tWpLdR5q4oFoK98Hgcye9wXEl2GNQJM5F7IqHjNVJrQFwawPrYJKLpV6aRaxlgc4dB467AsYMcQX7KhqBsyqkw5SZp/qasGB+58K/fzjah2Hvb8TdLcAAxELAnDcNVLtaUTJ7YnSDZzDtw3Al7KQLXT2ttlHO83ufhOaucfzG4w=,iv:+NDTpIVkhtPD/HTgLYHzhB7Sxo9vJvIknIvTNzxrlWM=,tag:rvNSU+EaEE8uQCHzPCOiSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:Lsv0,iv:EPyx7V/rPXWd9QRkcOXWhcDWKWp1IRs9EpCodPeumTY=,tag:qrdfLX/S6TFcw9XS92xpKQ==,type:str]
    password: ENC[AES256_GCM,data:CmWKsEbK8fS4dJvRCPZiYbt8GCnZuDLAawpxeeJRFKmLrUy1QlCVrwy17Ee1LMr/m5Re47R9nwqIl4FUB2uhHSyqrLAKEnB158nA9o2iLEPaMevCGADNcamktz/D,iv:rUianSNOatSYe96fW0XOi6Ruofss+QCN9LZr5Sacw0E=,tag:sznk+JgzslOgC+8m/jfMlw==,type:str]
kind: Secret
metadata:
    name: git-auth
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ0FqY21jSUFiM0dDTUhC
            dVE5Z09NZ2Z6VjRwNm43WWhxODBVYUJUZDBBClhGKzQxQUFtRzEzYkp4SEsyaS9s
            WWxKTXBLQlBXaGFtckNMTWFteWRoNEEKLS0tIG1LUE0xRzFLbDZaNDlaZW1KQUVJ
            bW9saVkwYUEvRVFaSDFLbzlXYWZuU3cKJC7oVVFXYxTbASgdReA8j/EpxccWuaFp
            7lPwK/STrevlEkUywmmK3pxPlLtujl0E7l5qu75ZgNIrPk7xEgjCkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T17:27:11Z"
    mac: ENC[AES256_GCM,data:tWpLdR5q4oFoK98Hgcye9wXEl2GNQJM5F7IqHjNVJrQFwawPrYJKLpV6aRaxlgc4dB467AsYMcQX7KhqBsyqkw5SZp/qasGB+58K/fzjah2Hvb8TdLcAAxELAnDcNVLtaUTJ7YnSDZzDtw3Al7KQLXT2ttlHO83ufhOaucfzG4w=,iv:+NDTpIVkhtPD/HTgLYHzhB7Sxo9vJvIknIvTNzxrlWM=,tag:rvNSU+EaEE8uQCHzPCOiSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
