---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: descheduler
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/descheduler/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: kube-system
  releaseName: descheduler
  chart:
    spec:
      chart: descheduler
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  interval: 1m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  values:
    schedule: "*/2 * * * *"
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
        effect: NoSchedule
    deschedulerPolicy:
      profiles:
        - name: restart-pods
          pluginConfig:
          - name: "PodLifeTime"
            args:
              maxPodLifeTimeSeconds: 43200
              states:
              - "Pending"
              - "PodInitializing"
              - "Running"
              evictableNamespaces:
                exclude:
                - flux-system
                - istio-system
                - kube-system
                - longhorn-system
                - velero
          plugins:
            deschedule:
              enabled:
                - "PodLifeTime"