---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    istio.io/dataplane-mode: ambient
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 72h
  url: oci://ghcr.io/traefik/helm/traefik
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: ">=40.0.0 <42.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  serviceAccountName: helm-controller
  targetNamespace: traefik
  releaseName: traefik
  chartRef:
    kind: OCIRepository
    name: traefik
  interval: 1m
  timeout: 5m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  #valuesFrom:
  #- kind: ConfigMap
  #  name: traefik-values
  #  valuesKey: values.yaml
  values:
    log:
      format: "common"
      level: "INFO"
    #logs:
    #  access:
    #    enabled: true
    #    format: "common"
    accessLog:
      enabled: true
    api:
      dashboard: false
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: '{{ template "traefik.name" . }}'
                app.kubernetes.io/instance: '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
            topologyKey: kubernetes.io/hostname
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
        effect: NoSchedule
    providers:
      kubernetesGateway:
        enabled: true
        labelSelector: "gateway=traefik"
      kubernetesCRD:
        enabled: true
        #safeNaming: true
      kubernetesIngress:
        enabled: false
    gateway:
      enabled: false
    gatewayClass:
      enabled: true
      name: traefik
      labels:
        gateway: traefik
    deployment:
      replicas: 2
    ingressClass:
      enabled: false
    updateStrategy:  # @schema additionalProperties: false
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1  # @schema type:[integer, string, null]
        maxSurge: 1        # @schema type:[integer, string, null]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    ports:
      web:
        port: 8000
        protocol: TCP
        expose:
          default: false
      websecure:
        port: 8443
        protocol: TCP
        expose:
          default: false
      http:
        asDefault:
        port: 9000
        expose:
          default: true
        exposedPort: 80
        targetPort:
        protocol: TCP
      https:
        port: 9443
        hostPort:
        containerPort:
        expose:
          default: true
        exposedPort: 443
        targetPort:
        protocol: TCP
    service:
      enabled: true

