# Source: https://github.com/kyverno/policies/blob/main/best-practices/add-network-policy/add-network-policy.yaml
# Author: Kyverno Project
# License: Apache 2.0
# Modifications: Adjusted namespace exclusion scope
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-deny-networkpolicy
  annotations:
    policies.kyverno.io/category: Workload Security and Governance Policies
spec:
  generateExisting: true
  rules:
    - name: default-deny
      match:
        any:
          - resources:
              kinds:
                - Namespace
      generate:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        name: default-deny
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
      exclude:
        any:
          - resources:
              namespaces:
                - flux-system
                - istio-system
                - kube-system
                - longhorn-system
                - velero
