apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - require-requests-limits.yaml
  - restrict-scheduling.yaml
  - verify-flux-images.yaml
  - verify-git-repositories.yaml
  - add-resources.yaml
  - protect-resourcequotas.yaml
  - deny-namespace-modification.yaml
  - restrict-image-registries.yaml
  - require-pod-probes.yaml
