# Source: https://github.com/kyverno/policies/blob/main/best-practices/restrict-node-port/restrict-node-port.yaml
# Author: Kyverno Project
# License: Apache 2.0
# Modifications: included a second rule to require that LoadBalancer Services set allocateLoadBalancerNodePorts to false
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-nodeport-and-lb-nodeports
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-nodeport
      match:
        any:
          - resources:
              kinds:
                - Service
      validate:
        message: Services of type NodePort are not allowed.
        pattern:
          spec:
            "=(type)": "!NodePort"
    - name: require-no-nodeports-for-loadbalancer
      match:
        any:
          - resources:
              kinds:
                - Service
      preconditions:
        all:
          - key: "{{ request.object.spec.type || 'ClusterIP' }}"
            operator: Equals
            value: LoadBalancer
      validate:
        message: LoadBalancer Services must set spec.allocateLoadBalancerNodePorts to false.
        pattern:
          spec:
            allocateLoadBalancerNodePorts: false