---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1m
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: istio-system
  releaseName: base
  chart:
    spec:
      version: "1.29.0"
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: istio-system
  releaseName: istiod
  chart:
    spec:
      version: "1.29.0"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  values:
    profile: "ambient"
    cni:
      ambient:
        ipv6: false
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      node-role.kubernetes.io/infra: ""
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: istio-system
  releaseName: istio-cni
  chart:
    spec:
      version: "1.29.0"
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  values:
    profile: "ambient"
    cni:
      ambient:
        ipv6: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: istio-system
  releaseName: ztunnel
  chart:
    spec:
      version: "1.29.0"
      chart: ztunnel
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  values:
    crds:
      enabled:
        true
    env:
      IPV6_ENABLED: "false"

