---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
# The installer describes the source of the installation.
installer:
    image: ${image} # Allows for supplying the image used to perform the installation.
# The provisioning describes how the installation disk should be provisioned.
provisioning:
    # Matches disks to initialize as physical volumes.
    diskSelector:
        match: disk.dev_path == "/dev/sda" # CEL expression matching a disk.
    wipe: false # Indicates if the installation disk should be wiped at installation time.