---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: openebs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs-localpv
  namespace: flux-system
spec:
  interval: 12h
  url: https://openebs.github.io/dynamic-localpv-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-localpv
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: openebs
  releaseName: openebs-localpv
  chart:
    spec:
      chart: localpv-provisioner
      version: "4.5.1"
      sourceRef:
        kind: HelmRepository
        name: openebs-localpv
        namespace: flux-system
  interval: 1m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  values:
    hostpathClass:
      enabled: true
      isDefaultClass: true
      basePath: "/var/mnt/longhorn"
    localpv:
      resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule