---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kubernetes-csi/external-snapshotter
  ref:
    tag: v8.5.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-crds
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: ./client/config/crd
  targetNamespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: snapshot-crds
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: ./deploy/kubernetes/snapshot-controller
  targetNamespace: kube-system

