---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    istio.io/dataplane-mode: ambient
  name: trivy-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  interval: 1m
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: trivy-system
  releaseName: trivy
  chart:
    spec:
      version: "0.31.0"
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: flux-system
  interval: 1m
  timeout: 15m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  values:
    excludeNamespaces: "kube-system,kube-public,kube-node-lease,kyverno,policy-reporter,trivy-system,trivy-adapter,longhorn-system,istio-system,flux-system"
  valuesFrom:
  - kind: ConfigMap
    name: trivy-operator-values
    valuesKey: values.yaml

